all:
  children:
    prod_db:
      hosts:
        db01.prod.example.local:
        db02.prod.example.local:
        db03.prod.example.local:
      vars:
        db_port: 5432
        environment: prod

    prod_app:
      hosts:
        app01.prod.example.local:
        app02.prod.example.local:
        app03.prod.example.local:
        app04.prod.example.local:
      vars:
        app_port: 8080
        environment: prod

    prod_web:
      hosts:
        web01.prod.example.local:
        web02.prod.example.local:
      vars:
        web_port: 443
        environment: prod
