all:
  children:
    prod_db:
      hosts:
        prod-db-01:
          ansible_host: 10.0.30.11
        prod-db-02:
          ansible_host: 10.0.30.12
    prod_app:
      hosts:
        prod-app-01:
          ansible_host: 10.0.30.21
        prod-app-02:
          ansible_host: 10.0.30.22
    prod_web:
      hosts:
        prod-web-01:
          ansible_host: 10.0.30.31
        prod-web-02:
          ansible_host: 10.0.30.32
