all:
  children:
    db:
      children:
        prod_db:
          children:
            prod_db_canary:
              hosts:
                db01.prod.example.local:
            prod_db_wave2:
              hosts:
                db02.prod.example.local:
            prod_db_final:
              hosts:
                db03.prod.example.local:

    app:
      children:
        prod_app:
          children:
            prod_app_canary:
              hosts:
                app01.prod.example.local:
            prod_app_wave2:
              hosts:
                app02.prod.example.local:
                app03.prod.example.local:
            prod_app_final:
              hosts:
                app04.prod.example.local:

    web:
      children:
        prod_web:
          children:
            prod_web_canary:
              hosts:
                web01.prod.example.local:
            prod_web_wave2:
              hosts:
                web02.prod.example.local:
            prod_web_final:
              hosts: {}
