---
stages:
  - dev
  - preprod
  - prod

variables:
  ANSIBLE_HOST_KEY_CHECKING: "False"
  ANSIBLE_FORCE_COLOR: "True"

.ansible_template: &ansible_base
  image: cytopia/ansible:latest
  before_script:
    - ansible --version
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

# ---------------- DEV ----------------
dev:db:
  <<: *ansible_base
  stage: dev
  script:
    - ansible-playbook -i inventory/dev/hosts.yml site.yml --limit dev_db
  environment:
    name: dev
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

dev:app:
  <<: *ansible_base
  stage: dev
  script:
    - ansible-playbook -i inventory/dev/hosts.yml site.yml --limit dev_app
  environment:
    name: dev
  needs:
    - job: dev:db
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

dev:web:
  <<: *ansible_base
  stage: dev
  script:
    - ansible-playbook -i inventory/dev/hosts.yml site.yml --limit dev_web
  environment:
    name: dev
  needs:
    - job: dev:app
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

# ---------------- PREPROD ----------------
preprod:db:
  <<: *ansible_base
  stage: preprod
  script:
    - ansible-playbook -i inventory/preprod/hosts.yml site.yml --limit preprod_db
  environment:
    name: preprod
  needs:
    - job: dev:web
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

preprod:app:
  <<: *ansible_base
  stage: preprod
  script:
    - ansible-playbook -i inventory/preprod/hosts.yml site.yml --limit preprod_app
  environment:
    name: preprod
  needs:
    - job: preprod:db
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

preprod:web:
  <<: *ansible_base
  stage: preprod
  script:
    - ansible-playbook -i inventory/preprod/hosts.yml site.yml --limit preprod_web
  environment:
    name: preprod
  needs:
    - job: preprod:app
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

# ---------------- PROD ----------------
prod:db:
  <<: *ansible_base
  stage: prod
  script:
    - ansible-playbook -i inventory/prod/hosts.yml site.yml --limit prod_db
  environment:
    name: prod
  needs:
    - job: preprod:web
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

prod:app:
  <<: *ansible_base
  stage: prod
  script:
    - ansible-playbook -i inventory/prod/hosts.yml site.yml --limit prod_app
  environment:
    name: prod
  needs:
    - job: prod:db
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

prod:web:
  <<: *ansible_base
  stage: prod
  script:
    - ansible-playbook -i inventory/prod/hosts.yml site.yml --limit prod_web
  environment:
    name: prod
  needs:
    - job: prod:app
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
