---
- name: Configure database servers
  hosts: all
  become: true
  roles:
    - db
  tags: db

- name: Configure application servers
  hosts: all
  become: true
  roles:
    - app
  tags: app

- name: Configure web servers
  hosts: all
  become: true
  roles:
    - web
  tags: web
