---
- name: Configure database servers
  hosts: db
  become: true
  roles:
    - db

- name: Configure application servers
  hosts: app
  become: true
  roles:
    - app

- name: Configure web servers
  hosts: web
  become: true
  roles:
    - web
