all:
  children:
    db:
      children:
        dev_db:
          children:
            dev_db_canary:
              hosts:
                db01.dev.example.local:
            dev_db_wave2:
              hosts:
                db02.dev.example.local:
            dev_db_final:
              hosts: {}

    app:
      children:
        dev_app:
          children:
            dev_app_canary:
              hosts:
                app01.dev.example.local:
            dev_app_wave2:
              hosts:
                app02.dev.example.local:
            dev_app_final:
              hosts:
                app03.dev.example.local:

    web:
      children:
        dev_web:
          children:
            dev_web_canary:
              hosts:
                web01.dev.example.local:
            dev_web_wave2:
              hosts: {}
            dev_web_final:
              hosts: {}
