all:
  children:
    dev_db:
      hosts:
        db01.dev.example.local:
        db02.dev.example.local:
      vars:
        db_port: 5432
        environment: dev

    dev_app:
      hosts:
        app01.dev.example.local:
        app02.dev.example.local:
        app03.dev.example.local:
      vars:
        app_port: 8080
        environment: dev

    dev_web:
      hosts:
        web01.dev.example.local:
      vars:
        web_port: 443
        environment: dev
