all:
  children:
    dev_db:
      hosts:
        db01.dev.example.local:
        db02.dev.example.local:

    dev_app:
      hosts:
        app01.dev.example.local:
        app02.dev.example.local:
        app03.dev.example.local:

    dev_web:
      hosts:
        web01.dev.example.local:
