all:
  children:
    preprod_db:
      hosts:
        preprod-db-01:
          ansible_host: 10.0.20.11
    preprod_app:
      hosts:
        preprod-app-01:
          ansible_host: 10.0.20.21
    preprod_web:
      hosts:
        preprod-web-01:
          ansible_host: 10.0.20.31
