all:
  children:
    db:
      children:
        preprod_db:
          hosts:
            db01.preprod.example.local:

    app:
      children:
        preprod_app:
          hosts:
            app01.preprod.example.local:
            app02.preprod.example.local:

    web:
      children:
        preprod_web:
          hosts:
            web01.preprod.example.local:
            web02.preprod.example.local:
