all:
  children:
    preprod_db:
      hosts:
        db01.preprod.example.local:
      vars:
        db_port: 5432
        environment: preprod

    preprod_app:
      hosts:
        app01.preprod.example.local:
        app02.preprod.example.local:
      vars:
        app_port: 8080
        environment: preprod

    preprod_web:
      hosts:
        web01.preprod.example.local:
        web02.preprod.example.local:
      vars:
        web_port: 443
        environment: preprod
